# Generated by Django 2.0.3 on 2018-06-22 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_author_blog_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encodings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='encodings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.UserInfo'),
        ),
    ]
