# Generated by Django 2.0.3 on 2018-06-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20180622_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='thapar_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
